### ISSUE TITLE
Cell specific peak files

### ISSUE THREAD

**Issue by gouthamatla** [hbliu/Kidney_Epi_Pri#1]
Hi All,

Excellent paper. I am just wondering where can I get the processed scATAC peaks per cell type ?

Thanks,
Goutham A

**Comment by hbliu** [comment]
Hi Goutham,
You may get these peaks by link https://figshare.com/ndownloader/files/41420238
Let me know if this link does not work for you.

Best,
Hongbo

**Comment by gouthamatla** [comment]
Thank you
